services:
  directus:
    image: directus/directus:11.6.1
    ports:
      - "${DIRECTUS_PORT}:8055"
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    environment:
      # Database Configuration
      #DATABASE_URL: ${DATABASE_URL}
      DB_CLIENT:  ${DB_CLIENT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SSL: '{"rejectUnauthorized": false}'


      # Directus Configuration
      KEY: ${DIRECTUS_KEY}
      SECRET: ${DIRECTUS_SECRET}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

      NODE_OPTIONS: "--dns-result-order=ipv4first"
      # Recommended for production
      PUBLIC_URL: ${PUBLIC_URL}

      # Optional settings
      CACHE_ENABLED: "true"
      RATE_LIMITER_ENABLED: "true"
      CORS_ENABLED: "true"
      CORS_ORIGIN: ${CORS_ORIGIN}

    restart: unless-stopped