services:
  directus:
    image: directus/directus:11.6.1
    ports:
       - ${PORT}:${PORT}
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    environment:
      # Database Configuration
      #DATABASE_URL: ${DATABASE_URL}
      NODE_OPTIONS: "--max_old_space_size=7096"
      DB_CLIENT:  ${DB_CLIENT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SSL: '{"rejectUnauthorized": false}'
      

      # Directus Configuration
      KEY: ${DIRECTUS_KEY}
      SECRET: ${DIRECTUS_SECRET}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

      # Recommended for production
      PUBLIC_URL: ${PUBLIC_URL}

      # Cache and file storage
      CACHE_ENABLED: ${CACHE_ENABLED:-true}
      CACHE_STORE: ${CACHE_STORE:-memory}
      STORAGE_LOCATIONS: ${STORAGE_LOCATIONS:-local}
      STORAGE_LOCAL_DRIVER: ${STORAGE_LOCAL_DRIVER:-local}
      STORAGE_LOCAL_ROOT: ${STORAGE_LOCAL_ROOT:-/directus/uploads}

      # Optional settings
      RATE_LIMITER_ENABLED: "true"
      CORS_ENABLED: "true"
      CORS_ORIGIN: ${CORS_ORIGIN}

    restart: unless-stopped